[unstable]
build-std-features = ["compiler-builtins-mem"]
build-std = ["core", "compiler_builtins"]

[build]
target = "x86_64-kennOS.json"

# `cargo run` will launch QEMU
[target.'cfg(target_os = "none")']
runner = "bootimage runner"